import React, { useEffect, useState } from 'react';
import { Icon } from '../components/Icon';
import { Ring } from '../components/Ring';
import { fetchDashboard } from '../lib/api';
import { DomainRow } from '../components/DomainRow';
export const DashboardScreen: React.FC<any> = ({ onOpenDomain, goToListWithFilter, toast: _toast }) => {
  const [data, setData] = useState<any>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { fetchDashboard().then(setData).catch(() => setData({totalDomains:42, expiring30:5, sslNear:3, noDmarc:7, avgHealth:78, topRisks:[{id:1,name:'risk.ru',health:12,daysLeft:2}], renewalBudget:125000, distribution:{'0-30':5,'30-90':12,'90+':25}})).finally(()=>setLoading(false)); }, []);
  if (loading || !data) return <div className="tg-pad">Загрузка...</div>;
  return <div className="tg-pad tg-pad-b"><div className="tg-card" style={{padding:18,display:'flex',alignItems:'center',gap:18}}><Ring value={data.avgHealth} size={92} stroke={9} label="из 100" /><div style={{flex:1}}><div className="tg-kpi-lbl" style={{marginBottom:4}}>Здоровье портфеля</div><div style={{fontSize:15,color:'var(--pv-fg-body)'}}>{data.avgHealth>=75?'Портфель в хорошем состоянии.':'Есть домены, требующие внимания.'}</div>{(data.expiring30||0)>0 && <button className="pv-btn pv-btn-sm" style={{marginTop:10}} onClick={() => goToListWithFilter && goToListWithFilter('soon')}>{data.expiring30} требуют действий</button>}</div></div><div className="tg-kpis" style={{marginTop:12}}><div className="tg-kpi" onClick={() => goToListWithFilter && goToListWithFilter('all')}><div className="tg-kpi-lbl"><Icon name="language" />Доменов</div><div className="tg-kpi-val">{data.totalDomains}</div></div><div className="tg-kpi" onClick={() => goToListWithFilter && goToListWithFilter('soon')}><div className="tg-kpi-lbl"><Icon name="hourglass_bottom" />Истекают &lt;30дн</div><div className="tg-kpi-val">{data.expiring30}</div></div><div className="tg-kpi" onClick={() => goToListWithFilter && goToListWithFilter('problem')}><div className="tg-kpi-lbl"><Icon name="lock_clock" />SSL &lt;90дн</div><div className="tg-kpi-val">{data.sslNear}</div></div><div className="tg-kpi" onClick={() => goToListWithFilter && goToListWithFilter('silent')}><div className="tg-kpi-lbl"><Icon name="mark_email_unread" />Без DMARC</div><div className="tg-kpi-val">{data.noDmarc}</div></div></div><div className="tg-card" style={{marginTop:12}}><div className="tg-card-title"><Icon name="donut_small" />Распределение по сроку</div><div className="tg-distbar">{Object.entries(data.distribution||{}).map(([_k,n]:any,i:number)=> <i key={i} style={{width:(n/data.totalDomains*100)+'%', background:i===0?'var(--pv-green)':i===1?'var(--pv-gold)':'var(--pv-red)'}} />)}</div></div><div className="tg-card" style={{marginTop:12}}><div className="tg-card-title">Бюджет продления</div><div style={{fontSize:28,fontWeight:700}}>{(data.renewalBudget||0).toLocaleString('ru-RU')} ₽/год</div></div><div className="tg-card" style={{marginTop:12}}><div className="tg-card-title">Топ-риски</div>{(data.topRisks||[]).map((d:any) => <DomainRow key={d.id} d={d} onOpen={onOpenDomain} />)}</div></div>;
};
