
import React from 'react';
import { Icon } from '../components/Icon';
import { fetchSettings } from '../lib/api';
const MoreRow = ({icon, color, label, sub, val, onClick, chev}: any) => <div className="tg-grp" onClick={onClick} style={{borderBottom:'1px solid var(--pv-divider)'}}><div className="tg-grp-ico" style={{width:38,height:38,background:color||'var(--pv-muted)'}}><Icon name={icon} /></div><div className="tg-grp-main"><div className="tg-grp-name">{label}</div>{sub && <div className="tg-grp-sub">{sub}</div>}</div>{val!=null && <span className="tg-grp-n">{val}</span>}{chev && <Icon name="chevron_right" style={{color:'var(--pv-fg-subtle)'}} />}</div>;
export const MoreScreen: React.FC<any> = ({ domains=[], go, toast: _toast, theme, setTheme }) => {
  const [user, setUser] = React.useState({name:'НМ',handle:'@user',plan:'Free'});
  React.useEffect(()=>{ fetchSettings().then(setUser).catch(()=>{}); },[]);
  const counts = {wish: (domains||[]).filter((d:any)=>d.isWishlist).length, total:(domains||[]).length };
  return <div className="tg-pad-b"><div style={{display:'flex',alignItems:'center',gap:14,padding:'18px 16px',background:'var(--pv-panel)',borderBottom:'1px solid var(--pv-border)'}}><div className="pv-avatar a1 lg" style={{width:52,height:52,fontSize:18}}>НМ</div><div style={{flex:1}}><div style={{fontSize:17,fontWeight:700}}>{user.name}</div><div style={{fontSize:13,color:'var(--pv-fg-muted)'}}>{user.handle} · {counts.total} доменов</div></div><span className="tg-pill" style={{background:'var(--pv-muted)',color:'var(--pv-fg-muted)'}}>{user.plan}</span></div><div className="tg-section-label">Организация</div><div className="tg-card" style={{margin:'0 12px',borderRadius:12}}><MoreRow icon="folder_special" color="#9c4bb5" label="Группы и теги" sub="Клиенты, проекты" onClick={()=>go({screen:'groups'})} chev /><MoreRow icon="target" color="#8e44ad" label="Wishlist" sub="Жду освобождения" val={counts.wish} onClick={()=>go({screen:'wishlist'})} chev /><MoreRow icon="insights" color="#27ae60" label="Статистика" sub="Сводка по портфелю" onClick={()=>go({screen:'stats'})} chev /></div><div className="tg-section-label">Данные</div><div className="tg-card" style={{margin:'0 12px',borderRadius:12}}><MoreRow icon="upload_file" color="#e67e22" label="Импорт доменов" sub="TXT или CSV" onClick={()=>go({screen:'import'})} chev /><MoreRow icon="download" color="#16a085" label="Экспорт в CSV" sub="Весь список" onClick={()=>_toast('Файл domains.csv готов','download')} chev /></div><div className="tg-section-label">Приложение</div><div className="tg-card" style={{margin:'0 12px',borderRadius:12}}><MoreRow icon="settings" color="#9c4bb5" label="Настройки" sub="Часовой пояс, напоминания" onClick={()=>go({screen:'settings'})} chev /><div className="tg-irow" style={{minHeight:56}}><div className="tg-grp-ico" style={{width:34,height:34,background:'var(--pv-fg)'}}><Icon name="dark_mode" style={{fontSize:18}} /></div><div style={{flex:1}}><div style={{fontSize:15,fontWeight:700}}>Тёмная тема</div><div style={{fontSize:12,color:'var(--pv-fg-muted)'}}>Следует теме Telegram</div></div><div className={"pv-toggle" + (theme==='dark'?" on":"")} onClick={()=>setTheme(theme==='dark'?'light':'dark')} /></div></div><div style={{textAlign:'center',padding:'24px 16px',color:'var(--pv-fg-subtle)',fontSize:12}}>Whois Watcher · v0.16.0<br />Бесплатный сервис · GitHub</div></div>;
};
export const GroupsScreen: React.FC<any> = ({go}) => <div className="tg-pad"><div className="tg-card">Группы (stub — TASK-0073)<button onClick={()=>go({tab:'list'})}>Назад</button></div></div>;
export const WishlistScreen: React.FC<any> = () => <div className="tg-pad"><div className="tg-card">Wishlist (stub)<button className="pv-btn" onClick={()=>console.log('Add (stub)')}>Добавить</button></div></div>;
export const StatsScreen: React.FC<any> = () => <div className="tg-pad"><div className="tg-card">Статистика (stub)</div></div>;
export const ImportScreen: React.FC<any> = () => <div className="tg-pad"><div className="tg-card">Импорт (stub)<button className="pv-btn" onClick={()=>console.log('Импорт (stub)')}>Выбрать файл</button></div></div>;
export const SettingsScreen: React.FC<any> = () => <div className="tg-pad"><div className="tg-card">Настройки (stub, write в 0070)</div></div>;
export const AddScreen: React.FC<any> = () => <div className="tg-pad"><input placeholder="домен" /><button className="pv-btn" onClick={()=>console.log('Добавлено (stub)')}>Добавить</button></div>;
