#!/usr/bin/env bash
# Generates src/_build_info.py with the current git state.
#
# Запускается ВРУЧНУЮ перед каждой docker-сборкой релиза — внутри
# контейнера .git/ нет, поэтому мы запекаем коммит/тэг/время в код заранее.
# См. docs/deployment.md "Обновление до новой версии".
set -euo pipefail
cd "$(dirname "$0")/.."

COMMIT=$(git rev-parse HEAD)
COMMIT_SHORT=$(git rev-parse --short HEAD)
BRANCH=$(git rev-parse --abbrev-ref HEAD)
BUILD_TIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
TAG=$(git describe --tags --exact-match HEAD 2>/dev/null || echo "")

# Версию пакета достаём из pyproject.toml через stdlib tomllib (Python 3.11+).
# В docker-образе ``--no-install-project`` → importlib.metadata не находит
# whois-watcher, поэтому /version полагается на это поле как primary source.
APP_VERSION=$(python3 -c "
import tomllib
with open('pyproject.toml', 'rb') as f:
    print(tomllib.load(f)['project']['version'])
")

cat > src/_build_info.py <<EOF
"""Auto-generated build info. Do not edit manually.

Generated by scripts/generate_build_info.sh before docker build.
File is gitignored — appears only in the built image.
"""
APP_VERSION = "${APP_VERSION}"
GIT_COMMIT = "${COMMIT}"
GIT_COMMIT_SHORT = "${COMMIT_SHORT}"
GIT_BRANCH = "${BRANCH}"
GIT_TAG = "${TAG}"
BUILD_TIME = "${BUILD_TIME}"
EOF

echo "Generated src/_build_info.py:"
cat src/_build_info.py
